---
name: Nebula VPN
version: "0.2.0"
slug: nebula_vpn
description: Nebula mesh VPN client for Home Assistant OS (x86_64 only)
url: https://github.com/clwhipp/nebula-hassio-addons
startup: services
boot: auto
panel_icon: mdi:vpn
arch:
  - amd64
init: false
host_network: true
privileged:
  - NET_ADMIN
devices:
  - /dev/net/tun
map:
  - config:rw
ports:
  4242/udp: null
options:
  ca_cert: ""
  host_cert: ""
  host_key: ""
  nebula_config: ""
  debug: false
schema:
  ca_cert: str
  host_cert: str
  host_key: password
  nebula_config: str
  debug: bool
image: "7cjqdceqvl3fbbj2/nebula-hassio-addon-amd64"
