---
name: Nebula VPN
version: "0.3.1"
slug: nebula_vpn
description: Nebula mesh VPN client for Home Assistant OS (x86_64 only)
url: https://github.com/clwhipp/nebula-hassio-addons
startup: services
boot: auto
panel_icon: mdi:vpn
arch:
  - amd64
init: false
host_network: true
privileged:
  - NET_ADMIN
devices:
  - /dev/net/tun
map:
  - type: ssl
    read_only: true
  - type: homeassistant_config
    read_only: false
    path: /config
ports:
  4242/udp: null
options:
  ca_cert_path: "/ssl/nebula/ca.crt"
  host_cert_path: "/ssl/nebula/host.crt"
  host_key_path: "/ssl/nebula/host.key"
  config_path: "/config/nebula/config.yml"
  debug: false
schema:
  ca_cert_path: str
  host_cert_path: str
  host_key_path: str
  config_path: str
  debug: bool
image: "7cjqdceqvl3fbbj2/nebula-hassio-addon-amd64"
